function plotagemPura(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3, YMATRIX4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 11-Aug-2016 09:13:39

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','X');
set(plot1(2),'DisplayName','Y');
set(plot1(3),'DisplayName','Z');

% Create title
title('Acelerometro','FontSize',11);

% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2);
set(plot2(1),'DisplayName','X');
set(plot2(2),'DisplayName','Y');
set(plot2(3),'DisplayName','Z');

% Create title
title('Giroscopio','FontSize',11);

% Create legend
legend(subplot2,'show');

% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',subplot3);
set(plot3(1),'DisplayName','X');
set(plot3(2),'DisplayName','Y');
set(plot3(3),'DisplayName','Z');

% Create title
title('Magnetometro','FontSize',11);

% Create legend
legend(subplot3,'show');

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
box(subplot4,'on');
grid(subplot4,'on');
hold(subplot4,'on');

% Create multiple lines using matrix input to plot
plot4 = plot(X1,YMatrix4,'Parent',subplot4);
set(plot4(1),'DisplayName','W');
set(plot4(2),'DisplayName','X');
set(plot4(3),'DisplayName','Y');
set(plot4(4),'DisplayName','Z');

% Create title
title('Quaternion','FontSize',11);

% Create legend
legend(subplot4,'show');

