function times_30Hz_28_09 = importtimes(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   TIMES_30HZ_28_09 = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   TIMES_30HZ_28_09 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   times_30Hz_28_09 = importfile('2016-09-28 09:44:48.898259-dados.txt',1, 6658);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/28 09:52:23

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{yyyy-MM-dd hh:mm:ss.SSSSSS}D)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{yyyy-MM-dd HH:mm:ss.SSSSSS}D%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    dataArray{1} = [dataArray{1};dataArrayBlock{1}];
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
times_30Hz_28_09 = dataArray{:, 1};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% times_30Hz_28_09=datenum(times_30Hz_28_09);


