# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(280, 570)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mbly = QtGui.QHBoxLayout()
        self.mbly.setObjectName(_fromUtf8("mbly"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupColeta = QtGui.QGroupBox(self.centralwidget)
        self.groupColeta.setObjectName(_fromUtf8("groupColeta"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupColeta)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cbSerialPort = QtGui.QComboBox(self.groupColeta)
        self.cbSerialPort.setObjectName(_fromUtf8("cbSerialPort"))
        self.verticalLayout_5.addWidget(self.cbSerialPort)
        self.btnAnimation = QtGui.QPushButton(self.groupColeta)
        self.btnAnimation.setObjectName(_fromUtf8("btnAnimation"))
        self.verticalLayout_5.addWidget(self.btnAnimation)
        self.btnColeta = QtGui.QPushButton(self.groupColeta)
        self.btnColeta.setObjectName(_fromUtf8("btnColeta"))
        self.verticalLayout_5.addWidget(self.btnColeta)
        self.btnMarcar = QtGui.QPushButton(self.groupColeta)
        self.btnMarcar.setObjectName(_fromUtf8("btnMarcar"))
        self.verticalLayout_5.addWidget(self.btnMarcar)
        self.verticalLayout_2.addWidget(self.groupColeta)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.groupRotation = QtGui.QGroupBox(self.centralwidget)
        self.groupRotation.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupRotation.setObjectName(_fromUtf8("groupRotation"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupRotation)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cbJointNames = QtGui.QComboBox(self.groupRotation)
        self.cbJointNames.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cbJointNames.setObjectName(_fromUtf8("cbJointNames"))
        self.verticalLayout.addWidget(self.cbJointNames)
        self.lbPhi = QtGui.QLabel(self.groupRotation)
        self.lbPhi.setObjectName(_fromUtf8("lbPhi"))
        self.verticalLayout.addWidget(self.lbPhi)
        self.slPhi = QtGui.QSlider(self.groupRotation)
        self.slPhi.setMinimum(-180)
        self.slPhi.setMaximum(180)
        self.slPhi.setOrientation(QtCore.Qt.Horizontal)
        self.slPhi.setObjectName(_fromUtf8("slPhi"))
        self.verticalLayout.addWidget(self.slPhi)
        self.lbTheta = QtGui.QLabel(self.groupRotation)
        self.lbTheta.setObjectName(_fromUtf8("lbTheta"))
        self.verticalLayout.addWidget(self.lbTheta)
        self.slTheta = QtGui.QSlider(self.groupRotation)
        self.slTheta.setMinimum(-180)
        self.slTheta.setMaximum(180)
        self.slTheta.setOrientation(QtCore.Qt.Horizontal)
        self.slTheta.setObjectName(_fromUtf8("slTheta"))
        self.verticalLayout.addWidget(self.slTheta)
        self.lbPsi = QtGui.QLabel(self.groupRotation)
        self.lbPsi.setObjectName(_fromUtf8("lbPsi"))
        self.verticalLayout.addWidget(self.lbPsi)
        self.slPsi = QtGui.QSlider(self.groupRotation)
        self.slPsi.setMinimum(-180)
        self.slPsi.setMaximum(180)
        self.slPsi.setProperty("value", 0)
        self.slPsi.setOrientation(QtCore.Qt.Horizontal)
        self.slPsi.setObjectName(_fromUtf8("slPsi"))
        self.verticalLayout.addWidget(self.slPsi)
        self.btnRotate = QtGui.QPushButton(self.groupRotation)
        self.btnRotate.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnRotate.setObjectName(_fromUtf8("btnRotate"))
        self.verticalLayout.addWidget(self.btnRotate)
        self.btnReset = QtGui.QPushButton(self.groupRotation)
        self.btnReset.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.verticalLayout.addWidget(self.btnReset)
        self.verticalLayout_2.addWidget(self.groupRotation)
        self.mbly.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.mbly)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 280, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuVisualizar = QtGui.QMenu(self.menubar)
        self.menuVisualizar.setObjectName(_fromUtf8("menuVisualizar"))
        self.menuGr_ficos = QtGui.QMenu(self.menuVisualizar)
        self.menuGr_ficos.setObjectName(_fromUtf8("menuGr_ficos"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_Postura = QtGui.QAction(MainWindow)
        self.actionAbrir_Postura.setObjectName(_fromUtf8("actionAbrir_Postura"))
        self.actionSalvar_Postura = QtGui.QAction(MainWindow)
        self.actionSalvar_Postura.setObjectName(_fromUtf8("actionSalvar_Postura"))
        self.actionMenu_de_Rota_o = QtGui.QAction(MainWindow)
        self.actionMenu_de_Rota_o.setObjectName(_fromUtf8("actionMenu_de_Rota_o"))
        self.action_rea_do_Tri_ngulo = QtGui.QAction(MainWindow)
        self.action_rea_do_Tri_ngulo.setObjectName(_fromUtf8("action_rea_do_Tri_ngulo"))
        self.actionPosi_o = QtGui.QAction(MainWindow)
        self.actionPosi_o.setObjectName(_fromUtf8("actionPosi_o"))
        self.actionQuaternion = QtGui.QAction(MainWindow)
        self.actionQuaternion.setObjectName(_fromUtf8("actionQuaternion"))
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionAbrir_Postura)
        self.menuArquivo.addAction(self.actionSalvar_Postura)
        self.menuGr_ficos.addAction(self.action_rea_do_Tri_ngulo)
        self.menuGr_ficos.addAction(self.actionPosi_o)
        self.menuGr_ficos.addAction(self.actionQuaternion)
        self.menuVisualizar.addAction(self.actionMenu_de_Rota_o)
        self.menuVisualizar.addAction(self.menuGr_ficos.menuAction())
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuVisualizar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupColeta.setTitle(_translate("MainWindow", "Coleta:", None))
        self.btnAnimation.setText(_translate("MainWindow", "Iniciar Animação", None))
        self.btnColeta.setText(_translate("MainWindow", "Iniciar Coleta", None))
        self.btnMarcar.setText(_translate("MainWindow", "Marcar", None))
        self.groupRotation.setTitle(_translate("MainWindow", "Rotação:", None))
        self.lbPhi.setText(_translate("MainWindow", "Phi", None))
        self.lbTheta.setText(_translate("MainWindow", "Theta", None))
        self.lbPsi.setText(_translate("MainWindow", "Psi", None))
        self.btnRotate.setText(_translate("MainWindow", "Rotate", None))
        self.btnReset.setText(_translate("MainWindow", "Reset", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuVisualizar.setTitle(_translate("MainWindow", "Visualizar", None))
        self.menuGr_ficos.setTitle(_translate("MainWindow", "Gráficos", None))
        self.actionAbrir_Postura.setText(_translate("MainWindow", "Abrir Postura", None))
        self.actionSalvar_Postura.setText(_translate("MainWindow", "Salvar Postura", None))
        self.actionMenu_de_Rota_o.setText(_translate("MainWindow", "Menu de Rotação", None))
        self.action_rea_do_Tri_ngulo.setText(_translate("MainWindow", "Área do Triângulo", None))
        self.actionPosi_o.setText(_translate("MainWindow", "Posição", None))
        self.actionQuaternion.setText(_translate("MainWindow", "Quaternion", None))

