using System;

public enum packetTypes
{
	UART_START_SIGNAL  = 0x53,
	UART_END_SIGNAL  = 0x04,

	UART_PACKET_TYPE_ACEL      = 0x01,
	UART_PACKET_TYPE_GIRO      = 0x02,
	UART_PACKET_TYPE_MAG       = 0x03,
	UART_PACKET_TYPE_M6        = 0x04,
	UART_PACKET_TYPE_M9        = 0x05,
	UART_PACKET_TYPE_QUAT      = 0x06,
	UART_PACKET_TYPE_FIFO_NO_MAG       = 0x07,
	UART_PACKET_TYPE_FIFO_ALL_READINGS     = 0x08,
	UART_PACKET_TYPE_STRING    = 0x09,
	UART_PACKET_TYPE_HEX       = 0x0A,
	UART_PACKET_TYPE_BIN       = 0x0B,
	UART_PACKET_TYPE_UINT16    = 0x0C,
	UART_PACKET_TYPE_INT16     = 0x0D,
	UART_PACKET_TYPE_FLOAT16       = 0x0E
}

